<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('product_barcodes', function (Blueprint $table) {
            $table->id();
            
            // Polymorphic relation - products, product variants & product uoms
            $table->morphs('barcodeable');
            
            // Barcode details
            $table->string('barcode', 50)->index(); // Allow up to 50 chars for flexibility
            $table->enum('barcode_type', [
                'EAN-13', 
                'EAN-8',
                'UPC-A', 
                'UPC-E',
                'CODE-128', 
                'CODE-39',
                'QR', 
                'INTERNAL',
                'SCALE' // For price-embedded barcodes
            ])->default('INTERNAL');
            
            // Priority & status
            $table->boolean('is_primary')->default(false); // Main barcode for this item
            $table->boolean('is_active')->default(true);
            
            // Context (for disambiguation)
            $table->foreignId('supplier_id')->nullable()->constrained('suppliers')->nullOnDelete();
            $table->string('region', 10)->nullable(); // KE, TZ, UG
            $table->foreignId('store_id')->nullable()->constrained('stores')->nullOnDelete();
            
            // Validity period
            $table->date('valid_from')->nullable();
            $table->date('valid_until')->nullable();
            
            // Source tracking
            $table->enum('source', [
                'manufacturer', 
                'manual', 
                'generated', 
                'supplier', 
                'imported',
                'scale' // Generated by weighing scale
            ])->default('manual');
            
            // Metadata
            $table->json('metadata')->nullable(); // Store additional info (e.g., scale format details)
            $table->text('notes')->nullable();
            $table->timestamps();
            $table->softDeletes(); // Don't hard-delete barcodes
            
            // INDEXES
            $table->index(['barcode', 'is_active', 'store_id'], 'idx_barcode_lookup');
            $table->index(['barcodeable_type', 'barcodeable_id', 'is_primary'], 'idx_entity_barcodes');
            $table->index(['is_active', 'valid_from', 'valid_until'], 'idx_active_valid');
            
            // Prevent duplicate active barcodes in same context
            $table->unique(
                ['barcode', 'store_id', 'supplier_id', 'is_active'], 
                'unique_active_barcode_context'
            );
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('product_barcodes');
    }
};
