<?php

namespace App\Services\Tenant\Supplier;

use App\Enums\Tenant\PaymentStatus;
use App\Models\Tenant\PurchaseOrder;
use App\Models\Tenant\Supplier;
use App\Models\Tenant\SupplierPayment;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class SupplierPaymentService
{
    /**
     * Record new supplier payment
     *
     * @param array $data
     * @return SupplierPayment
     * @throws \RuntimeException
     */
    public function recordPayment(array $data): SupplierPayment
    {
        return DB::transaction(function () use ($data) {
            // 1. Lock and validate supplier
            $supplier = Supplier::lockForUpdate()->findOrFail($data['supplier_id']);

            if (!$supplier->is_active) {
                throw new \RuntimeException('Cannot record payment for inactive supplier');
            }

            // 2. If PO linked, validate and lock it
            $purchaseOrder = null;
            if (!empty($data['purchase_order_id'])) {
                $purchaseOrder = PurchaseOrder::lockForUpdate()
                    ->findOrFail($data['purchase_order_id']);

                // Validate PO belongs to supplier
                if ($purchaseOrder->supplier_id !== $supplier->id) {
                    throw new \RuntimeException('Purchase order does not belong to this supplier');
                }

                // Validate PO is in valid status
                if (!$purchaseOrder->status->canReceivePayment()) {
                    throw new \RuntimeException(
                        "Cannot record payment for PO with status: {$purchaseOrder->status->label()}"
                    );
                }

                // Calculate PO outstanding
                $poOutstanding = $purchaseOrder->total_amount - $purchaseOrder->amount_paid;

                // Validate payment doesn't exceed PO outstanding
                if ($data['amount'] > $poOutstanding) {
                    throw new \RuntimeException(
                        sprintf(
                            "Payment amount (%.2f) exceeds PO outstanding balance (%.2f)",
                            $data['amount'],
                            $poOutstanding
                        )
                    );
                }
            }

            // 3. Validate payment doesn't exceed supplier outstanding
            if ($data['amount'] > $supplier->outstanding_balance) {
                throw new \RuntimeException(
                    sprintf(
                        "Payment amount (%.2f) exceeds supplier outstanding balance (%.2f)",
                        $data['amount'],
                        $supplier->outstanding_balance
                    )
                );
            }

            // 4. Handle receipt upload if provided
            $receiptPath = null;
            if (!empty($data['receipt'])) {
                $receiptPath = $this->storeReceipt($data['receipt']);
            }

            // 5. Create payment record (payment_number will be auto-generated by observer)
            $payment = SupplierPayment::create([
                'supplier_id' => $supplier->id,
                'purchase_order_id' => $purchaseOrder?->id,
                'payment_date' => $data['payment_date'],
                'amount' => $data['amount'],
                'payment_method' => $data['payment_method'],
                'reference_number' => $data['reference_number'] ?? null,
                'notes' => $data['notes'] ?? null,
                'receipt_path' => $receiptPath,
                'created_by' => Auth::id(),
            ]);

            // 6. Update supplier outstanding balance (DECREMENT)
            $supplier->decrement('outstanding_balance', $data['amount']);

            // 7. If PO linked, update PO payment tracking
            if ($purchaseOrder) {
                $newAmountPaid = $purchaseOrder->amount_paid + $data['amount'];
                $purchaseOrder->update([
                    'amount_paid' => $newAmountPaid,
                ]);

                // Update PO payment status
                $this->updatePurchaseOrderPaymentStatus($purchaseOrder);
            }

            Log::info('Supplier payment recorded successfully', [
                'payment_id' => $payment->id,
                'payment_number' => $payment->payment_number,
                'supplier_id' => $supplier->id,
                'supplier_name' => $supplier->name,
                'po_id' => $purchaseOrder?->id,
                'po_number' => $purchaseOrder?->po_number,
                'amount' => $data['amount'],
                'payment_method' => $data['payment_method'],
                'supplier_new_balance' => $supplier->fresh()->outstanding_balance,
                'tenant_id' => tenant()->id ?? 'system',
            ]);

            return $payment->fresh(['supplier', 'purchaseOrder', 'createdBy']);
        });
    }

    /**
     * Get supplier payments with filters
     *
     * @param int $supplierId
     * @param array $filters
     * @return LengthAwarePaginator
     */
    public function getSupplierPayments(int $supplierId, array $filters = []): LengthAwarePaginator
    {
        $query = SupplierPayment::withDetails()
            ->bySupplier($supplierId);

        // Apply filters
        if (!empty($filters['purchase_order_id'])) {
            $query->byPurchaseOrder($filters['purchase_order_id']);
        }

        if (!empty($filters['payment_method'])) {
            $query->byPaymentMethod($filters['payment_method']);
        }

        if (!empty($filters['from_date']) || !empty($filters['to_date'])) {
            $query->byDateRange($filters['from_date'] ?? null, $filters['to_date'] ?? null);
        }

        $query->recent();

        // Pagination
        $perPage = $filters['per_page'] ?? 20;

        return $query->paginate($perPage);
    }

    /**
     * Get purchase order payments
     *
     * @param int $poId
     * @return Collection
     */
    public function getPurchaseOrderPayments(int $poId): Collection
    {
        return SupplierPayment::withDetails()
            ->byPurchaseOrder($poId)
            ->recent()
            ->get();
    }

    /**
     * Get supplier payment summary
     *
     * @param int $supplierId
     * @param int|null $poId
     * @return array
     */
    public function getSupplierPaymentSummary(int $supplierId, ?int $poId = null): array
    {
        $query = SupplierPayment::where('supplier_id', $supplierId);

        if ($poId) {
            $query->where('purchase_order_id', $poId);
        }

        $payments = $query->get();

        $totalPaid = $payments->sum('amount');
        $paymentCount = $payments->count();

        $byMethod = $payments->groupBy('payment_method')
            ->map(function ($group) {
                return [
                    'method' => $group->first()->payment_method->value,
                    'method_label' => $group->first()->payment_method->label(),
                    'count' => $group->count(),
                    'total' => round($group->sum('amount'), 2),
                ];
            })
            ->values()
            ->toArray();

        return [
            'supplier_id' => $supplierId,
            'purchase_order_id' => $poId,
            'total_paid' => round($totalPaid, 2),
            'payment_count' => $paymentCount,
            'by_method' => $byMethod,
            'currency' => 'KES',
        ];
    }

    /**
     * Store payment receipt file
     *
     * @param \Illuminate\Http\UploadedFile $file
     * @return string
     */
    private function storeReceipt($file): string
    {
        // Generate unique filename
        $filename = sprintf(
            '%s_%s.%s',
            'receipt',
            time(),
            $file->getClientOriginalExtension()
        );

        // Store in tenant-isolated storage
        $path = $file->storeAs(
            'supplier-payments/receipts',
            $filename,
            'public' // Use tenant disk
        );

        Log::info('Supplier payment receipt stored', [
            'path' => $path,
            'filename' => $filename,
            'tenant_id' => tenant()->id ?? 'system',
        ]);

        return $path;
    }

    /**
     * Update purchase order payment status based on amount paid
     *
     * @param PurchaseOrder $po
     * @return void
     */
    private function updatePurchaseOrderPaymentStatus(PurchaseOrder $po): void
    {
        $totalAmount = $po->total_amount;
        $amountPaid = $po->amount_paid;

        $oldStatus = $po->payment_status;

        if ($amountPaid <= 0) {
            $newStatus = PaymentStatus::UNPAID;
        } elseif ($amountPaid >= $totalAmount) {
            $newStatus = PaymentStatus::PAID;
        } else {
            $newStatus = PaymentStatus::PARTIALLY_PAID;
        }

        if ($oldStatus !== $newStatus) {
            $po->update(['payment_status' => $newStatus]);

            Log::info('Purchase order payment status updated', [
                'po_id' => $po->id,
                'po_number' => $po->po_number,
                'old_status' => $oldStatus->value,
                'new_status' => $newStatus->value,
                'amount_paid' => $amountPaid,
                'total_amount' => $totalAmount,
                'outstanding' => $totalAmount - $amountPaid,
                'tenant_id' => tenant()->id ?? 'system',
            ]);
        }
    }
}
